name: Pull Request CI

on:
  pull_request:

jobs:
#  lint:
#    name: Lint
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#      - name: Set up Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: '20'
#      - name: Install frontend dependencies
#        working-directory: ./frontend
#        run: npm install
#      - name: Lint frontend
#        working-directory: ./frontend
#        run: npm run lint

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install
      - name: Run frontend unit tests
        working-directory: ./frontend
        run: npm run test
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Make mvnw executable
        run: chmod +x backend/main/mvnw
      - name: Run backend unit tests
        working-directory: ./backend/main
        run: ./mvnw test

  e2e-test:
    name: E2E Tests
    runs-on: ubuntu-latest
    environment: staging
    env:
      SUPABASE_URL: ${{ secrets.STAGING_SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.STAGING_SUPABASE_KEY }}
      E2E_USERNAME_ID: ${{ secrets.STAGING_E2E_USERNAME_ID }}
      E2E_USERNAME: ${{ secrets.STAGING_E2E_USERNAME }}
      E2E_PASSWORD: ${{ secrets.STAGING_E2E_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Install Playwright browsers
        working-directory: ./frontend
        run: npx playwright install --with-deps

      - name: Generate environment.staging.ts from secrets
        working-directory: ./frontend
        run: |
          mkdir -p src/environments
          cat > src/environments/environment.staging.ts <<EOF
          export const environment = {
            production: false,
            supabaseUrl: '${SUPABASE_URL}',
            supabaseKey: '${SUPABASE_KEY}',
            e2eUsernameId: '${E2E_USERNAME_ID}',
            e2eUsername: '${E2E_USERNAME}',
            e2ePassword: '${E2E_PASSWORD}'
          };
          EOF

      - name: Run e2e tests
        working-directory: ./frontend
        run: npm run test:e2e
